name: Run Tests
run-name: Run Tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Scala
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install scala
      - name: Install Valgrind
        run: |
          sudo apt install -y valgrind
      - name: Add llvm-as to PATH
        run: |
          echo "/usr/lib/llvm-14/bin" >> $GITHUB_PATH
      - name: Check llvm-as availability
        run: |
          llvm-as --version
      - name: Run `make test`
        run: |
          export SDKMAN_DIR="$HOME/.sdkman"
          [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
          make test
        timeout-minutes: 5
